server:
  port: 8081
  servlet:
    context-path: /mqf
spring:
  profiles:
    active: dev
debug: true


---
server:
  port: 8086
spring:
  profiles: dev

---
server:
  port: 8086
spring:
  profiles: prod